app/profile/__init__.py
# Creating a blueprint for profile pages
from flask import Blueprint
bp = Blueprint('profile', __name__)
from app.profile import routes

app/profile/routes.py
from flask import render_template, redirect, url_for, flash, request
from flask_login import login_required, logout_user

from app.profile import bp
from app.app_utils import LOGGER, get_current_user, update_user_record, delete_user_record
from app.forms.base_form import ProfileForm

# ==============================================================================================================
# User Profile Pages
# ============================================================================================================== 
@bp.route('/')
@login_required
def index():
    '''
    Retrieves the users profile info

    Parameter(s):
        User must be logged in

    Output(s):
        Redirects to the home page if  is None, else redirects to the user's profile page
    '''
    user = get_current_user()
    # Check if the user is logged in
    if not user:
        return redirect(url_for('auth.index'))
    
    # Get the data upon the first instance of the key
    #user = get_user_record(user_id=user_id)
    return render_template('./profile/view_profile.html', nav_id="home-page", user=user, username=user.username)

# ==============================================================================================================
@bp.route('/edit_profile', methods=['GET','POST'])
@login_required
def edit_profile():
    '''
    Updates the users credentials
    
    Parameter(s): 
        User must be logged in

    Output(s):
        An html page for editing profile info if logged in or post fails, else redirects to login page
    '''
    try:
        user = get_current_user()
        if not user:
            return redirect(url_for('auth.index'))
    
        form = ProfileForm(form=request.form)
        # Check Form validation
        if form.validate_on_submit():

            status = update_user_record(
                user_id=user.id, 
                username=form.username.data, 
                email=form.email.data, 
                password=form.password.data
            )

            # Check if the profile was successfully updated
            if status:
                flash("Update Successful!", "success")
                return redirect(url_for('profile.index'))
            else:
                raise Exception("Update failed")        

    except Exception as e:
        LOGGER.error(f'An error occurred when updating record: {e}')
        flash("Failed to update record!", "error")
        
    return render_template('./profile/edit_profile.html', nav_id="home-page", user=user, username=user.username, form=form)

# ==============================================================================================================
@bp.route("/delete_profile")
@login_required
def delete_profile():
    '''
    Deletes the user's profile from the database

    Parameter(s):
        User must be logged in

    Output(s):
        None, redirects to the manage page
    '''
    try:
        user = get_current_user()
        if not user:
            return redirect(url_for('auth.index'))
        
        # Query database for question and delete it
        status = delete_user_record(user_id=user.id)

        if status:
            logout_user()
            flash("Profile deleted successfully!", "success")
            return redirect(url_for('main.index'))
        else:
            raise Exception("Deletion failed")
            
    except Exception as e:
        LOGGER.error(f'An Error occured when deleting the record: {str(e)}')
        flash("Failed to delete profile!", "error")
    
    return redirect(url_for('profile.index'))

app/templates/profile/edit_profile.html
{% extends "base.html" %}

{% block title %}Edit Profile{% endblock %}

{% block content %}
<form class="record-form shadow" action="{{ url_for('profile.edit_profile') }}" method="post" enctype="multipart/form-data">
    {{ form.csrf_token }}
    {{ form.id(value=user.id) }}
    <div class="form-topic">
        {{ form.username.label(class='title') }}
        
        {% if form.username.errors %}
            {{ form.username(class='error-element', value=user.name | escape) }}
            <p class="error-message">{{ form.username.errors[0] }}</p>
        {% else %}
            {{ form.username(value=user.name | escape) }}
        {% endif %}
    </div>
    <div class="form-topic">
        {{ form.email.label(class='title') }}

        {% if form.email.errors %}
            {{ form.email(class='error-element', value=user.email | escape) }}
            <p class="error-message">{{ form.email.errors[0] }}</p>
        {% else %}
            {{ form.email(value=user.email | escape) }}
        {% endif %}
    </div>
    <div class="form-topic">
        {{ form.password.label(class='title') }}

        {% if form.password.errors %}
            {{ form.password(class='error-element') }}
            <p class="error-message">{{ form.password.errors[0] }}</p>
        {% else %}
            {{ form.password }}
        {% endif %}
    </div>
    <div class="form-topic">
        {{ form.confirm.label(class='title') }}

        {% if form.confirm.errors %}
            {{ form.confirm(class='error-element') }}
            <p class="error-message">{{ form.confirm.errors[0] }}</p>
        {% else %}
            {{ form.confirm }}
        {% endif %}
    </div>
    <button class="link center" type="submit">Update Profile</button>
</form>
{% endblock %}

app/templates/profile/view_profile.html
{% extends "base.html" %}

{% block title %}View Profile{% endblock %}

{% block content %}
<div class="topic">
    <div>
        <div class="title center-txt">Username</div>
        <div class="description center-txt">{{ user.name | escape }}</div>
    </div>
    <div>
        <div class="title center-txt">Email</div>
        <div class="description center-txt">{{ user.email | escape }}</div>
    </div>
    <div>
        <div class="title center-txt">Date Created</div>
        <div class="description center-txt">{{ user.created_on | escape }}</div>
    </div>

    <a class="link center-txt" href="{{ url_for('profile.edit_profile') | escape }}">
        Edit Profile
    </a>
    <a class="link center-txt delete-cell" href="#" data-record="{{ user.id | escape }}">
        Delete Profile
    </a>
</div>
{% endblock %}

{% block scripts %}
<script>
    // Confirm deletion of the queried question before deleting it
    document.querySelectorAll('.delete-cell').forEach(function (element) {
        element.addEventListener('click', function () {
            confirmDelete(element.dataset.record);
        });
    });

    // Display window prompt
    function confirmDelete(element) {
        var record = element;
        var result = confirm("Are you sure you want to delete this record?");
        if (result) {
            window.location.href = "delete_profile";
        }
    };
</script>
{% endblock %}